export default [
  { name: "Paris", address: "16 Villa Gaudelet, 75011 Paris", slug: "paris" },
  { name: "London", address: "14-22 Elder St, London E1 6BT", slug: "london" },
  { name: "Berlin", address: "Rudi-Dutschke-Straße 26, 10969 Berlin", slug: "berlin" },
  { name: "Bali", address: "Jalan Raya Batu Bolong, Canggu, Badung Regency, Bali, Indonesia", slug: "bali" },
  { name: "Budapest", address: "Budapest, Hungary", slug: "budapest" },
  { name: "Montréal", address: "5333, avenue Casgrain, 102, Montréal (Québec), H2T1X3", slug: "montreal" },
  { name: "Tokyo", address: "2-11-3 Meguro, Meguro-ku, Tokyo ", slug: "tokyo" },
  { name: "Amsterdam", address: "Overhoeksplein 2, 1031 KS Amsterdam", slug: "amsterdam" },
  { name: "Shanghai", address: "129 West Yan\"an Road, JingAn District, Shanghai", slug: "shanghai" },
  { name: "Brussels", address: "Place Sainte-Gudule 5, 1000 Brussels", slug: "brussels" },
  { name: "Lisbon", address: "Avenida Casal Ribeiro 28, Lisbon", slug: "lisbon" },
  { name: "Florianópolis", address: "Rod. José Carlos Daux, 4150 - Saco Grande, Florianópolis - SC, 88032-005", slug: "florianopolis" },
  { name: "Chengdu", address: "399 Fucheng Avenue West Section, Chengdu, Sichuan, China", slug: "chengdu" },
  { name: "Milan", address: "Milan, Metropolitan City of Milan, Italy", slug: "milan" },
  { name: "Rio de Janeiro", address: "Rua Duque Estrada, 41 - Gávea, Rio de Janeiro", slug: "rio" },
  { name: "Belo Horizonte", address: "Av. Afonso Pena, 2881, Belo Horizonte", slug: "belo-horizonte" },
  { name: "São Paulo", address: "Rua Mourato Coelho, 1404 – Vila Madalena, São Paulo - SP", slug: "sao-paulo" },
  { name: "Barcelona", address: "Travessera de Dalt, 33, 08024 Barcelona", slug: "barcelona" },
  { name: "Copenhagen", address: "Ahornsgade 15, 2200 KBH N", slug: "copenhagen" },
  { name: "Nantes", address: "11 impasse Juton, Nantes", slug: "nantes" },
  { name: "Aix - Marseille", address: "Rue Joseph Biaggi, 13003 Marseille", slug: "aix-marseille" },
  { name: "Bordeaux", address: "107 cours Balguerie Stuttenberg, 33300", slug: "bordeaux" },
  { name: "Lille", address: "2 Avenue des Saules, 59000 Lille", slug: "lille" },
  { name: "Lyon", address: "23 Rue Paul Montrochet, 69002 Lyon", slug: "lyon" }
];
